exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("venue")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("venue").insert([
        {
          name: "Altria Theater",
          address: "6 N Laurel St",
          city: "Richmond",
          state: "VA",
          zipcode: "23220",
          phone: "804-592-3368",
          social: "@altriatheaterva",
          website: "https://www.altriatheater.com",
        },
        {
          name: "Dominion Energy Center",
          address: "600 E Grace St",
          city: "Richmond",
          state: "VA",
          zipcode: "23219",
          phone: "804-592-3330",
          social: "@dominionenergycenter",
          website: "https://www.dominionenergycenter.com",
        },
        {
          name: "Gallery5",
          address: "200 W Marshall St",
          city: "Richmond",
          state: "VA",
          zipcode: "23220",
          phone: "---",
          social: "@gallery5arts",
          website: "https://gallery5arts.org",
        },
        {
          name: "Hippodrome Theater",
          address: "528 N 2nd St",
          city: "Richmond",
          state: "VA",
          zipcode: "23219",
          phone: "804-308-2913",
          social: "@hippodromerva",
          website: "https://hippodromerichmond.com",
        },
        {
          name: "Orbital Music Park",
          address: "Richmond, VA, USA",
          phone: "804-484-4136",
          social: "@orbitalmusicpark",
          website: "https://www.orbitalmusicpark.com/",
        },
        {
          name: "Richmond Music Hall",
          address: "619 E Main St",
          city: "Richmond",
          state: "VA",
          zipcode: "23219",
          phone: "(804) 780-2537",
          social: "@richmondmusichall",
          website: "http://www.capitalalehouse.com/richmond-music-hall/",
        },
        {
          name: "The Broadberry",
          address: "2729 W Broad St",
          city: "Richmond",
          state: "VA",
          zipcode: "23220",
          phone: "804-353-1888",
          social: "@thebroadberry",
          website: "https://thebroadberry.com",
        },
        {
          name: "The Camel",
          address: "1621 W Broad St",
          city: "Richmond",
          state: "VA",
          zipcode: "23220",
          phone: "804-353-4901",
          social: "@thecamelrva",
          website: "https://thecamel.org",
        },
        {
          name: "The Canal Club",
          address: "1545 E Cary St",
          city: "Richmond",
          state: "VA",
          zipcode: "23219",
          phone: "804-643-2582",
          social: "@thecanalclub",
          website: "https://thecanalclub.com",
        },
        {
          name: "The National",
          address: "708 E Broad St",
          city: "Richmond",
          state: "VA",
          zipcode: "23219",
          phone: "(804) 612-1900",
          social: "@thenationalva",
          website: "https://www.thenationalva.com/",
        },
        {
          name: "The Tin Pan",
          address: "8982 Quioccasin Rd",
          city: "Richmond",
          state: "VA",
          zipcode: "23229",
          phone: "804-447-8189",
          social: "@tinpanrva",
          website: "https://tinpanrva.com",
        },
        {
          name: "Vagabond",
          address: "700 E. Broad Street",
          city: "Richmond",
          state: "VA",
          zipcode: "23219",
          phone: "(804) 643-2632",
          social: "@vagabondrichmond",
          website: "http://vagabondrva.com/",
        },
        {
          name: "Virginia Credit Union Live",
          address: "900 E Laburnum Ave",
          city: "Richmond",
          state: "VA",
          zipcode: "23222",
          phone: "804-228-7500",
          social: "@vaculive",
          website: "https://www.vaculive.com",
        },
        {
          name: "Wonderland",
          address: "1727 E Main St",
          city: "Richmond",
          state: "VA",
          zipcode: "23223",
          phone: "(804) 643-9233",
          social: "@wonderlandrva",
          website: "https://www.facebook.com/Wonderland-RVA-236078742848/",
        },
      ]);
    });
};
